import { primitive } from "./Primitive.js";

const { base, brand, error, gray, success, warning } = primitive.color;
const light = gray.lightMode;

/** Raw palette tokens for direct use in component styles. */
export const colors = primitive.color;

/**
 * Semantic and component tokens, resolved from `primitive` rather than CSS
 * variable references so they work in React Native styles.
 */
export const Color = {
  primitive: colors,
  text: {
    primary900: light[900],
    secondary700: light[700],
    tertiary600: light[600],
    disabled: light[500],
    placeholder: light[500],
    placeholderSubtle: light[300],
    secondaryHover: light[800],
    tertiaryHover: light[700],
    quaternary500: light[500],
    white: base.white,
    errorPrimary600: error[600],
    warningPrimary600: warning[600],
    successPrimary600: success[600],
    brandSecondary700: brand[700],
    brandTertiary600: brand[600],
    brandPrimary900: brand[900],
    primaryOnBrand: base.white,
    secondaryOnBrand: brand[200],
    tertiaryOnBrand: brand[200],
  },
  border: {
    primary: light[300],
    secondary: light[200],
    tertiary: light[100],
    disabled: light[300],
    disabledSubtle: light[200],
    brand: brand[300],
    brandSolid: brand[600],
    brandSolidAlt: brand[600],
    error: error[300],
    errorSolid: error[600],
  },
  background: {
    primary: base.white,
    primaryAlt: base.white,
    primaryHover: light[50],
    primarySolid: light[950],
    secondary: light[50],
    secondaryAlt: light[50],
    secondaryHover: light[100],
    secondarySubtle: light[25],
    tertiary: light[100],
    quaternary: light[200],
    active: light[50],
    disabled: light[100],
    disabledSubtle: light[50],
    overlay: light[950],
    brandPrimary: brand[50],
    brandPrimaryAlt: brand[50],
    brandSecondary: brand[100],
    brandSolid: brand[600],
    brandSolidHover: brand[700],
    brandSection: brand[800],
    brandSectionSubtle: brand[700],
    errorPrimary: error[50],
    errorSecondary: error[100],
    errorSolid: error[600],
    warningPrimary: warning[50],
    warningSecondary: warning[100],
    warningSolid: warning[600],
    successPrimary: success[50],
    successSecondary: success[100],
    successSolid: success[600],
  },
  foreground: {
    white: base.white,
    primary900: light[900],
    secondary700: light[700],
    secondaryHover: light[800],
    tertiary600: light[600],
    tertiaryHover: light[700],
    quaternary500: light[500],
    quaternaryHover: light[600],
    quinary400: light[400],
    quinaryHover: light[500],
    senary300: light[300],
    disabled: light[400],
    disabledSubtle: light[300],
    brandPrimary600: brand[600],
    brandPrimaryAlt: brand[600],
    brandSecondary500: brand[500],
    errorPrimary: error[600],
    errorSecondary: error[500],
    warningPrimary: warning[600],
    warningSecondary: warning[500],
    successPrimary: success[600],
    successSecondary: success[500],
  },
  component: {
    button: {
      primary: {
        background: brand[600],
        backgroundHover: brand[700],
        foreground: base.white,
        border: brand[600],
        borderHover: brand[700],
      },
      secondary: {
        background: base.white,
        backgroundHover: light[50],
        foreground: light[700],
        foregroundHover: light[800],
        border: light[300],
        borderHover: light[300],
      },
      secondaryColor: {
        background: base.white,
        backgroundHover: brand[50],
        foreground: brand[700],
        foregroundHover: brand[800],
        border: brand[300],
        borderHover: brand[300],
      },
      primaryError: {
        background: error[600],
        backgroundHover: error[700],
        foreground: base.white,
        border: error[600],
        borderHover: error[700],
      },
      secondaryError: {
        background: base.white,
        backgroundHover: error[50],
        foreground: error[700],
        foregroundHover: error[800],
        border: error[300],
        borderHover: error[300],
      },
    },
    alpha: { white: base.white, black: base.black },
  },
} as const;
